// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tinthanh.Data.EF;

#nullable disable

namespace Tinthanh.data.Migrations
{
    [DbContext(typeof(TinthanhDBContext))]
    [Migration("20250202031442_Update1")]
    partial class Update1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tinthanh.Data.Entities.BanggiaKH", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Donvi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("Giaao")
                        .HasColumnType("float");

                    b.Property<double?>("Giaban")
                        .HasColumnType("float");

                    b.Property<double?>("Giabannt")
                        .HasColumnType("float");

                    b.Property<double?>("Giacu")
                        .HasColumnType("float");

                    b.Property<double?>("GiacuNT")
                        .HasColumnType("float");

                    b.Property<double?>("Giale")
                        .HasColumnType("float");

                    b.Property<string>("Khomay")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Makh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Marieng")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Masp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("Matdo")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Ngaycapnhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngaygiagoc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SoCAV")
                        .HasColumnType("int");

                    b.Property<string>("TenSPKH")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenSPTT")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short?>("Trangthai")
                        .HasColumnType("smallint");

                    b.Property<double?>("Trongluong")
                        .HasColumnType("float");

                    b.Property<string>("Users")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Masp", "Makh")
                        .IsUnique();

                    b.ToTable("BanggiaKH", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.BanggiaNCC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Baohanh")
                        .HasColumnType("int");

                    b.Property<double?>("Chietkhau")
                        .HasColumnType("float");

                    b.Property<double?>("ChietkhauSP")
                        .HasColumnType("float");

                    b.Property<string>("Donvi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ghichu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("Giaban")
                        .HasColumnType("float");

                    b.Property<double?>("Giacu")
                        .HasColumnType("float");

                    b.Property<bool?>("Hoadon")
                        .HasColumnType("bit");

                    b.Property<string>("MaDT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaVT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgayUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("ROHS")
                        .HasColumnType("bit");

                    b.Property<string>("TenNB")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenVT")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("TienChietKhau")
                        .HasColumnType("float");

                    b.Property<string>("Users")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("VAT")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MaVT", "MaDT")
                        .IsUnique();

                    b.ToTable("BanggiaNCC", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Banggiale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Donvi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<float?>("Giaban")
                        .HasColumnType("real");

                    b.Property<string>("Khomay")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Masp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float?>("Matdo")
                        .HasColumnType("real");

                    b.Property<DateTime?>("NgayUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenSP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float?>("Users")
                        .HasMaxLength(20)
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Masp")
                        .IsUnique()
                        .HasFilter("[Masp] IS NOT NULL");

                    b.ToTable("Banggiale", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Bophan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ma")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("Sanxuat")
                        .HasColumnType("bit");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Thuoc")
                        .HasColumnType("int");

                    b.Property<string>("Truongbophan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique()
                        .HasFilter("[Ma] IS NOT NULL");

                    b.ToTable("Bophan", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Chucnang", b =>
                {
                    b.Property<int>("Ma")
                        .HasColumnType("int");

                    b.Property<bool?>("IsCaption")
                        .HasColumnType("bit");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Thuoc")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.ToTable("Chucnang", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.CongviecBT", b =>
                {
                    b.Property<int>("Ma")
                        .HasColumnType("int");

                    b.Property<bool?>("Baotrixe")
                        .HasColumnType("bit");

                    b.Property<string>("Dungcu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsValue")
                        .HasColumnType("bit");

                    b.Property<bool?>("Ngungsd")
                        .HasColumnType("bit");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Ma");

                    b.ToTable("Congviec_BT", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Dangkiem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Giatri")
                        .HasColumnType("float");

                    b.Property<string>("Loai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Madt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("Ngayct")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngaydenhan")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Ngungsd")
                        .HasColumnType("bit");

                    b.Property<string>("Nhacc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Soct")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sohieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tailieu")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Tennhacc")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Madt" }, "IX_Dangkiem");

                    b.ToTable("Dangkiem", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Danhmuc", b =>
                {
                    b.Property<int>("Ma")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Ma");

                    b.ToTable("Danhmuc", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.DanhmucCT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DanhmucId")
                        .HasColumnType("int");

                    b.Property<bool>("Ngungsd")
                        .HasColumnType("bit");

                    b.Property<int>("STT")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DanhmucId");

                    b.ToTable("DanhmucCTs");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.DanhmucKT", b =>
                {
                    b.Property<int>("Ma")
                        .HasColumnType("int");

                    b.Property<string>("Chuanmuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Ngungsd")
                        .HasColumnType("bit");

                    b.Property<string>("Phuongphap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tansuat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Thuchien")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Ma");

                    b.ToTable("Danhmuc_KT", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.DateDim", b =>
                {
                    b.Property<DateTime>("TheDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Has53Weeks")
                        .HasColumnType("int");

                    b.Property<bool?>("IsLeapYear")
                        .HasColumnType("bit");

                    b.Property<int>("IsWeekend")
                        .HasColumnType("int");

                    b.Property<string>("MMYYYY")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Style101")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Style103")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Style112")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Style120")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TheDay")
                        .HasColumnType("int");

                    b.Property<string>("TheDayName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TheDayOfWeek")
                        .HasColumnType("int");

                    b.Property<byte?>("TheDayOfWeekInMonth")
                        .HasColumnType("tinyint");

                    b.Property<int?>("TheDayOfYear")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TheFirstOfMonth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TheFirstOfNextMonth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TheFirstOfQuarter")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TheFirstOfWeek")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TheFirstOfYear")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TheLastOfMonth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TheLastOfNextMonth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TheLastOfQuarter")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TheLastOfWeek")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TheLastOfYear")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TheMonth")
                        .HasColumnType("int");

                    b.Property<string>("TheMonthName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TheQuarter")
                        .HasColumnType("int");

                    b.Property<int?>("TheWeek")
                        .HasColumnType("int");

                    b.Property<byte?>("TheWeekOfMonth")
                        .HasColumnType("tinyint");

                    b.Property<int?>("TheYear")
                        .HasColumnType("int");

                    b.HasKey("TheDate");

                    b.ToTable("DateDim", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Donvi", b =>
                {
                    b.Property<string>("Ma")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("Ngungsd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Ma");

                    b.ToTable("Donvi", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.DonviVattu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Dongia")
                        .HasColumnType("float");

                    b.Property<string>("Donvi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Heso")
                        .HasColumnType("float");

                    b.Property<bool?>("Ngungsd")
                        .HasColumnType("bit");

                    b.Property<double?>("Trongluong")
                        .HasColumnType("float");

                    b.Property<int?>("VattuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VattuId");

                    b.ToTable("DonviVattu");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Donvisanpham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Dongia")
                        .HasColumnType("float");

                    b.Property<string>("Donvi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("Giakho")
                        .HasColumnType("float");

                    b.Property<double?>("Heso")
                        .HasColumnType("float");

                    b.Property<bool?>("Ngungsd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ThanhphamId")
                        .HasColumnType("int");

                    b.Property<double?>("Trongluong")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ThanhphamId");

                    b.ToTable("Donvisanpham", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Hethong", b =>
                {
                    b.Property<string>("Macty")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Diachi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Dienthoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("KSDenngay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Masothue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SongayKS")
                        .HasColumnType("int");

                    b.Property<string>("Tencty")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Macty");

                    b.ToTable("Hethong");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Khachhang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Congty")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Dagiao")
                        .HasColumnType("float");

                    b.Property<string>("Diachi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Dienthoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Donhang")
                        .HasColumnType("float");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ghichu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("HanTT")
                        .HasColumnType("int");

                    b.Property<bool?>("Hoadon")
                        .HasColumnType("bit");

                    b.Property<bool?>("Ingia")
                        .HasColumnType("bit");

                    b.Property<int?>("Ketu")
                        .HasColumnType("int");

                    b.Property<string>("Lienhe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LinkNhaCC")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Loaicn")
                        .HasColumnType("int");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Makv")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<string>("Manhom")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("Maxno")
                        .HasColumnType("float");

                    b.Property<string>("Msthue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Ngayngungsd")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Ngungsd")
                        .HasColumnType("bit");

                    b.Property<int?>("PTVanchuyen")
                        .HasColumnType("int");

                    b.Property<double?>("Soducongno")
                        .HasColumnType("float");

                    b.Property<int?>("Songay")
                        .HasColumnType("int");

                    b.Property<string>("Taikhoan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tentat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("ThanhtoanNH")
                        .HasColumnType("bit");

                    b.Property<bool?>("TheodoiCN")
                        .HasColumnType("bit");

                    b.Property<int?>("Thuoc")
                        .HasColumnType("int");

                    b.Property<bool?>("Thuongxuyen")
                        .HasColumnType("bit");

                    b.Property<int?>("TileTT")
                        .HasColumnType("int");

                    b.Property<string>("Users")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("VAT")
                        .HasColumnType("bit");

                    b.Property<string>("Website")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.HasIndex(new[] { "Manhom" }, "IX_Khachhang");

                    b.ToTable("Khachhang", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.KhachhangTN", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dienthoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lienhe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("Ngayngungsd")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Ngungsd")
                        .HasColumnType("bit");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Users")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Website")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("KhachhangTN", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Kho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diachi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dienthoai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Kho_ao")
                        .HasColumnType("bit");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Macu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Manhom")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("Ngayngungsd")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Ngungsd")
                        .HasColumnType("bit");

                    b.Property<string>("Taikhoan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tentat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Users")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("vitri")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("Kho", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Khomay", b =>
                {
                    b.Property<int>("Ma")
                        .HasColumnType("int");

                    b.Property<double?>("Giakhuon")
                        .HasColumnType("float");

                    b.Property<double?>("GiakhuonUSD")
                        .HasColumnType("float");

                    b.Property<double?>("Loinhuan")
                        .HasColumnType("float");

                    b.Property<double?>("LoinhuanM")
                        .HasColumnType("float");

                    b.Property<bool?>("Ngungsd")
                        .HasColumnType("bit");

                    b.Property<string>("Ten")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Ma");

                    b.ToTable("Khomay", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Khuon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short?>("Chuky")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ghichu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Khomay")
                        .HasColumnType("int");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Make")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Makh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Manhom")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Mats")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("Ngungsd")
                        .HasColumnType("bit");

                    b.Property<float?>("SanluongBT")
                        .HasColumnType("real");

                    b.Property<float?>("SanluonggiaKH")
                        .HasColumnType("real");

                    b.Property<short?>("SoCav")
                        .HasColumnType("smallint");

                    b.Property<short?>("SongayBT")
                        .HasColumnType("smallint");

                    b.Property<short?>("TGlenkhuon")
                        .HasColumnType("smallint");

                    b.Property<short?>("TGxuongkhuon")
                        .HasColumnType("smallint");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenKH")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tentat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float?>("ThoigiangiaKH")
                        .HasColumnType("real");

                    b.Property<short?>("Tilevon")
                        .HasColumnType("smallint");

                    b.Property<float?>("Trongluong")
                        .HasColumnType("real");

                    b.Property<string>("Users")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.HasIndex(new[] { "Manhom" }, "IX_Nhomkhuon");

                    b.ToTable("Khuon", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.KhuonBG", b =>
                {
                    b.Property<string>("Ma")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Ngungsd")
                        .HasColumnType("bit");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Ma");

                    b.ToTable("KhuonBG", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.KhuonCT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("CaoA")
                        .HasColumnType("float");

                    b.Property<double?>("CaoD")
                        .HasColumnType("float");

                    b.Property<double?>("Caont")
                        .HasColumnType("float");

                    b.Property<double?>("Caospa")
                        .HasColumnType("float");

                    b.Property<double?>("Caospd")
                        .HasColumnType("float");

                    b.Property<double?>("DaiA")
                        .HasColumnType("float");

                    b.Property<double?>("DaiD")
                        .HasColumnType("float");

                    b.Property<double?>("Daint")
                        .HasColumnType("float");

                    b.Property<double?>("Daispa")
                        .HasColumnType("float");

                    b.Property<double?>("Daispd")
                        .HasColumnType("float");

                    b.Property<string>("Donvi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("KhuonId")
                        .HasColumnType("int");

                    b.Property<string>("Masp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Nhom")
                        .HasColumnType("int");

                    b.Property<double?>("RongA")
                        .HasColumnType("float");

                    b.Property<double?>("RongD")
                        .HasColumnType("float");

                    b.Property<double?>("Rongnt")
                        .HasColumnType("float");

                    b.Property<double?>("Rongspa")
                        .HasColumnType("float");

                    b.Property<double?>("Rongspd")
                        .HasColumnType("float");

                    b.Property<bool?>("SPchinh")
                        .HasColumnType("bit");

                    b.Property<short?>("Socav")
                        .HasColumnType("smallint");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("KhuonId");

                    b.ToTable("Khuon_CT", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Khuvuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Macu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Ngoainuoc")
                        .HasColumnType("bit");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("Khuvuc", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.LienlacKH", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bophan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Chinhanh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Chucvu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Diachi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Didong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Dienthoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("EInvoice")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Hoten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("KhachhangId")
                        .HasColumnType("int");

                    b.Property<bool?>("Ngungsd")
                        .HasColumnType("bit");

                    b.Property<string>("Phanloai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PhanloaiId")
                        .HasColumnType("int");

                    b.Property<bool?>("Quyetdinh")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("KhachhangId");

                    b.ToTable("LienlacKH");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.LienlacNCC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bophan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Chinhanh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Chucvu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Diachi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Didong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Dienthoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("EInvoice")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ma")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Ngungsd")
                        .HasColumnType("bit");

                    b.Property<int>("NhacungcapId")
                        .HasColumnType("int");

                    b.Property<string>("Phanloai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PhanloaiId")
                        .HasColumnType("int");

                    b.Property<bool?>("Quyetdinh")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NhacungcapId");

                    b.ToTable("LienlacNCC", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Loaidanhdiem", b =>
                {
                    b.Property<string>("Ma")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Ma");

                    b.ToTable("Loaidanhdiem", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Loaidoituong", b =>
                {
                    b.Property<string>("Ma")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Ma");

                    b.ToTable("Loaidoituong", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Loaitaisan", b =>
                {
                    b.Property<string>("Ma")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Ma");

                    b.ToTable("Loaitaisan", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.MaymocTB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Baotri")
                        .HasColumnType("bit");

                    b.Property<bool?>("Baotringoai")
                        .HasColumnType("bit");

                    b.Property<string>("Bienlai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Congdung")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ghichu")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("Hanbaohanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HanbaotriDB")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Kiemdinh")
                        .HasColumnType("bit");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Manhom")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Mats")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Model")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NamSX")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayngungSD")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Nghiemnhat")
                        .HasColumnType("bit");

                    b.Property<bool?>("Ngungsd")
                        .HasColumnType("bit");

                    b.Property<string>("NhaSX")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NuocSX")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sohieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Soxacnhan")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<float?>("Taitrong")
                        .HasColumnType("real");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tentat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Thongso")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short?>("Trongluong")
                        .HasColumnType("smallint");

                    b.Property<string>("Users")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Vitri")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Xuatdau")
                        .HasColumnType("bit");

                    b.Property<string>("sochetao")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.HasIndex(new[] { "Manhom" }, "IX_NhomMaymoc");

                    b.ToTable("MaymocTB", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Nganhang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Congty")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dienthoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Manhom")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Msthue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Ngayngungsd")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Ngungsd")
                        .HasColumnType("bit");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Tentat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Users")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Website")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("Nganhang", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Nhacungcap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Dagiao")
                        .HasColumnType("float");

                    b.Property<string>("Diachi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dienthoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Donhang")
                        .HasColumnType("float");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ghichu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("HanTT")
                        .HasColumnType("int");

                    b.Property<bool?>("Hoadon")
                        .HasColumnType("bit");

                    b.Property<bool?>("ISO")
                        .HasColumnType("bit");

                    b.Property<string>("Linkkh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Manhom")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("Maxno")
                        .HasColumnType("float");

                    b.Property<string>("Msthue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Ngayngungsd")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Ngungsd")
                        .HasColumnType("bit");

                    b.Property<int?>("PTVanchuyen")
                        .HasColumnType("int");

                    b.Property<double?>("Soducongno")
                        .HasColumnType("float");

                    b.Property<string>("Taikhoan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tentat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("ThanhtoanNH")
                        .HasColumnType("bit");

                    b.Property<bool?>("TheodoiCN")
                        .HasColumnType("bit");

                    b.Property<int?>("TileTT")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Users")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("VAT")
                        .HasColumnType("bit");

                    b.Property<string>("Website")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.HasIndex(new[] { "Manhom" }, "IX_NhomNhacungcap");

                    b.ToTable("Nhacungcap", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Nhomdanhdiem", b =>
                {
                    b.Property<string>("Ma")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Madd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("Ngungsd")
                        .HasColumnType("bit");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Ma");

                    b.HasIndex("Madd");

                    b.ToTable("Nhomdanhdiem", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Nhomdoituong", b =>
                {
                    b.Property<string>("Ma")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Madt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("Ngungsd")
                        .HasColumnType("bit");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Ma");

                    b.HasIndex("Madt");

                    b.ToTable("Nhomdoituong", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Nhomtaisan", b =>
                {
                    b.Property<string>("Ma")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Mats")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("Ngungsd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Ma");

                    b.HasIndex("Mats");

                    b.ToTable("Nhomtaisan", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Tailieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Madt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Mota")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Ngungsd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Nhomtaileu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phanloai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tenfile")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Nhomtaileu" }, "IX_Nhomtailieu");

                    b.HasIndex(new[] { "Madt" }, "IX_Tailieu");

                    b.ToTable("Tailieu", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Taisan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bophansd")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ghichu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<float?>("GiatriKH")
                        .HasColumnType("real");

                    b.Property<float?>("GiatriKHLK")
                        .HasColumnType("real");

                    b.Property<float?>("Giatrithanhly")
                        .HasColumnType("real");

                    b.Property<bool?>("Hachtoan")
                        .HasColumnType("bit");

                    b.Property<string>("Loaits")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Manhom")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Mats")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgaySD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaybatdauKH")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayhetKH")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayngungSD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngaythanhly")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("NgungKH")
                        .HasColumnType("bit");

                    b.Property<bool?>("Ngungsd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("Nguongoc")
                        .HasColumnType("int");

                    b.Property<float?>("Nguyengia")
                        .HasColumnType("real");

                    b.Property<int?>("TGKhauhao")
                        .HasColumnType("int");

                    b.Property<string>("TKKhauhao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TKNguyengia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("TenTS")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tentat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float?>("TileKH")
                        .HasColumnType("real");

                    b.Property<int?>("Tinhtrang")
                        .HasColumnType("int");

                    b.Property<string>("Users")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Ma" }, "IX_Taisan")
                        .IsUnique();

                    b.HasIndex(new[] { "Manhom" }, "IX_TaisanNhom");

                    b.ToTable("Taisan", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Thanhpham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Ban")
                        .HasColumnType("bit");

                    b.Property<double?>("Cao")
                        .HasColumnType("float");

                    b.Property<bool?>("Cohinh")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Dai")
                        .HasColumnType("float");

                    b.Property<string>("Donvi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ghichu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("Hesobo")
                        .HasColumnType("float");

                    b.Property<string>("Kho")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Mabo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Manhom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Mua")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Ngayngungsd")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Ngungsd")
                        .HasColumnType("bit");

                    b.Property<string>("Quycach")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Rong")
                        .HasColumnType("float");

                    b.Property<string>("TKkho")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TKphi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tentat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Thetich")
                        .HasColumnType("float");

                    b.Property<int?>("Tinhgia")
                        .HasColumnType("int");

                    b.Property<double?>("Titrong")
                        .HasColumnType("float");

                    b.Property<bool?>("Ton")
                        .HasColumnType("bit");

                    b.Property<double?>("Tonmax")
                        .HasColumnType("float");

                    b.Property<double?>("Tonmin")
                        .HasColumnType("float");

                    b.Property<double?>("Tonreq")
                        .HasColumnType("float");

                    b.Property<double?>("Trongluong")
                        .HasColumnType("float");

                    b.Property<string>("Users")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.HasIndex(new[] { "Manhom" }, "IX_Nhomthanhpham");

                    b.ToTable("Thanhpham", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.ThanhphamBG", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Donvi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("Ngungsd")
                        .HasColumnType("bit");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Users")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("ThanhphamBG", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.TieuchiCT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaKT")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TieuchiKTMa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TieuchiKTMa");

                    b.ToTable("TieuchiCT", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.TieuchiKT", b =>
                {
                    b.Property<int>("Ma")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Ma");

                    b.ToTable("TieuchiKT");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.User", b =>
                {
                    b.Property<string>("Ma")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Bophan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsSuperUser")
                        .HasColumnType("bit");

                    b.Property<bool?>("Locked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Ngaytao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Ma");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.User_CT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int?>("Quyen")
                        .HasColumnType("int");

                    b.Property<string>("TenMenu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsersMa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("UsersMa");

                    b.ToTable("User_CT", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Vattu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Ban")
                        .HasColumnType("bit");

                    b.Property<double?>("Cao")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Dai")
                        .HasColumnType("float");

                    b.Property<string>("Donvi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ghichu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Kho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Loainhua")
                        .HasColumnType("int");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Macu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Manhom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Mua")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Ngayngungsd")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Ngungsd")
                        .HasColumnType("bit");

                    b.Property<bool?>("Nhapkhau")
                        .HasColumnType("bit");

                    b.Property<string>("Quycach")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Rong")
                        .HasColumnType("float");

                    b.Property<string>("TKkho")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TKphi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tentat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Thetich")
                        .HasColumnType("float");

                    b.Property<int?>("TieuchiKT")
                        .HasColumnType("int");

                    b.Property<double?>("Titrong")
                        .HasColumnType("float");

                    b.Property<bool?>("Ton")
                        .HasColumnType("bit");

                    b.Property<double?>("Tonmax")
                        .HasColumnType("float");

                    b.Property<double?>("Tonmin")
                        .HasColumnType("float");

                    b.Property<double?>("Tonreq")
                        .HasColumnType("float");

                    b.Property<double?>("Trongluong")
                        .HasColumnType("float");

                    b.Property<string>("Users")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Xuatxu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.HasIndex(new[] { "Manhom" }, "IX_NhomVattu");

                    b.ToTable("Vattu", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.XeBaoTri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Congviec")
                        .HasColumnType("int");

                    b.Property<string>("Ghichu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Hinhthuc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("Sogio")
                        .HasColumnType("float");

                    b.Property<int?>("Sogiodau")
                        .HasColumnType("int");

                    b.Property<int?>("Sokm")
                        .HasColumnType("int");

                    b.Property<double?>("Sokmdau")
                        .HasColumnType("float");

                    b.Property<string>("Soxe")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("XemayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("XemayId");

                    b.ToTable("Xe_Baotri", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.XeHoatdong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ghichu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Sogio")
                        .HasColumnType("float");

                    b.Property<double?>("Sokm")
                        .HasColumnType("float");

                    b.Property<string>("Soxe")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("XemayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("XemayId");

                    b.ToTable("Xe_Hoatdong", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Xemay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Baohiem")
                        .HasColumnType("bit");

                    b.Property<bool?>("Baotri")
                        .HasColumnType("bit");

                    b.Property<string>("Bienso")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<double?>("Dinhmucdau")
                        .HasColumnType("float");

                    b.Property<string>("EditBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ghichu")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("Hanbaohanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HanbaotriDB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Hancavet")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kichthuocthung")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Kiemdinh")
                        .HasColumnType("bit");

                    b.Property<string>("Loaithung")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("Mabuchi")
                        .HasColumnType("bit");

                    b.Property<string>("Manhom")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Mats")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Model")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NamSX")
                        .HasColumnType("int");

                    b.Property<int>("Namdangky")
                        .HasColumnType("int");

                    b.Property<int>("Namhethan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayngungSD")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Ngungsd")
                        .HasColumnType("bit");

                    b.Property<string>("NhaSX")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NuocSX")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<short?>("Socho")
                        .HasColumnType("smallint");

                    b.Property<string>("Sokhung")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Somay")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<double?>("Taitrong")
                        .HasColumnType("float");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tentat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Thetichthung")
                        .HasColumnType("float");

                    b.Property<short?>("Trongluong")
                        .HasColumnType("smallint");

                    b.Property<bool?>("Xegiaohang")
                        .HasColumnType("bit");

                    b.Property<bool?>("Xuatdau")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.HasIndex(new[] { "Manhom" }, "IX_NhomXemay");

                    b.ToTable("Xemay", (string)null);
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.DanhmucCT", b =>
                {
                    b.HasOne("Tinthanh.Data.Entities.Danhmuc", "Danhmuc")
                        .WithMany("DanhmucCTs")
                        .HasForeignKey("DanhmucId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Danhmuc");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.DonviVattu", b =>
                {
                    b.HasOne("Tinthanh.Data.Entities.Vattu", "Vattu")
                        .WithMany("DonviVattus")
                        .HasForeignKey("VattuId");

                    b.Navigation("Vattu");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Donvisanpham", b =>
                {
                    b.HasOne("Tinthanh.Data.Entities.Thanhpham", "Thanhpham")
                        .WithMany("Donvisanphams")
                        .HasForeignKey("ThanhphamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thanhpham");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.KhuonCT", b =>
                {
                    b.HasOne("Tinthanh.Data.Entities.Khuon", "Khuon")
                        .WithMany("KhuonCTs")
                        .HasForeignKey("KhuonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Khuon");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.LienlacKH", b =>
                {
                    b.HasOne("Tinthanh.Data.Entities.Khachhang", "Khachhang")
                        .WithMany("LienlacKHs")
                        .HasForeignKey("KhachhangId");

                    b.Navigation("Khachhang");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.LienlacNCC", b =>
                {
                    b.HasOne("Tinthanh.Data.Entities.Nhacungcap", "Nhacungcap")
                        .WithMany("LienlacNCCs")
                        .HasForeignKey("NhacungcapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nhacungcap");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Nhomdanhdiem", b =>
                {
                    b.HasOne("Tinthanh.Data.Entities.Loaidanhdiem", "Loaidanhdiem")
                        .WithMany("Nhomdanhdiems")
                        .HasForeignKey("Madd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loaidanhdiem");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Nhomdoituong", b =>
                {
                    b.HasOne("Tinthanh.Data.Entities.Loaidoituong", "Loaidoituong")
                        .WithMany("Nhomdoituongs")
                        .HasForeignKey("Madt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loaidoituong");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Nhomtaisan", b =>
                {
                    b.HasOne("Tinthanh.Data.Entities.Loaitaisan", "Loaitaisan")
                        .WithMany("Nhomtaisans")
                        .HasForeignKey("Mats");

                    b.Navigation("Loaitaisan");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.TieuchiCT", b =>
                {
                    b.HasOne("Tinthanh.Data.Entities.TieuchiKT", "TieuchiKT")
                        .WithMany("TieuchiCTs")
                        .HasForeignKey("TieuchiKTMa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TieuchiKT");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.User_CT", b =>
                {
                    b.HasOne("Tinthanh.Data.Entities.User", "User")
                        .WithMany("UserCTs")
                        .HasForeignKey("UsersMa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.XeBaoTri", b =>
                {
                    b.HasOne("Tinthanh.Data.Entities.Xemay", "Xemay")
                        .WithMany("XeBaoTris")
                        .HasForeignKey("XemayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Xemay");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.XeHoatdong", b =>
                {
                    b.HasOne("Tinthanh.Data.Entities.Xemay", "Xemay")
                        .WithMany("XeHoatdongs")
                        .HasForeignKey("XemayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Xemay");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Danhmuc", b =>
                {
                    b.Navigation("DanhmucCTs");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Khachhang", b =>
                {
                    b.Navigation("LienlacKHs");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Khuon", b =>
                {
                    b.Navigation("KhuonCTs");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Loaidanhdiem", b =>
                {
                    b.Navigation("Nhomdanhdiems");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Loaidoituong", b =>
                {
                    b.Navigation("Nhomdoituongs");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Loaitaisan", b =>
                {
                    b.Navigation("Nhomtaisans");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Nhacungcap", b =>
                {
                    b.Navigation("LienlacNCCs");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Thanhpham", b =>
                {
                    b.Navigation("Donvisanphams");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.TieuchiKT", b =>
                {
                    b.Navigation("TieuchiCTs");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.User", b =>
                {
                    b.Navigation("UserCTs");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Vattu", b =>
                {
                    b.Navigation("DonviVattus");
                });

            modelBuilder.Entity("Tinthanh.Data.Entities.Xemay", b =>
                {
                    b.Navigation("XeBaoTris");

                    b.Navigation("XeHoatdongs");
                });
#pragma warning restore 612, 618
        }
    }
}
