USE [TinthanhNew]
GO

INSERT INTO [dbo].[MaymocTB]
           ([Ma]
           ,[Ten]
           ,[Tentat]
           ,[Manhom]
           ,[NhaSX]
           ,[NamSX]
           ,[Sohieu]
           ,[NuocSX]
           ,[Baotri]
           ,[NgaySD]
           ,[Ghichu]
           ,[NgayngungSD]
           ,[EditBy]
           ,[EditDate]
            
           ,[Kiemdinh]
           ,[Hanbaohanh]
           ,[HanbaotriDB]
           ,[Ngungsd]
           ,[Model]
           ,[Thongso]
           ,[sochetao]
           ,[Trongluong]
           ,[Taitrong]
           ,[Congdung]
           ,[Soxacnhan]
           ,[Bienlai]
           ,[Nghiemnhat]
           ,[Vitri]
           ,[Xuatdau]
           ,[Mats]
           ,[Baotringoai])
    
SELECT [Ma]
           ,[Ten]
           ,[Tentat]
           ,[Manhom]
           ,[NhaSX]
           ,isnull([NamSX],'')
           ,[Sohieu]
           ,[NuocSX]
           ,[Baotri]
           ,[NgaySD]
           ,[Ghichu]
           ,[NgayngungSD]
           ,[EditBy]
           ,[EditDate]
         
           ,[Kiemdinh]
           ,[Hanbaohanh]
           ,[HanbaotriDB]
           ,[Ngungsd]
           ,[Model]
           ,[Thongso]
           ,[sochetao]
           ,[Trongluong]
           ,[Taitrong]
           ,[Congdung]
           ,[Soxacnhan]
           ,[Bienlai]
           ,[Nghiemnhat]
           ,[Vitri]
           ,[Xuatdau]
           ,[Macu]
           ,[Baotringoai] 
  FROM [TinthanhERP].[dbo].[MaymocTB]
