USE [Tinthanh]
GO

INSERT INTO tinthanhnew.dbo.[Phieubaogia]
           ([Maphieu]
           ,[Ngaylap]
           ,[Makh]
           ,[Tenkh]
           ,[Ghichu]
           ,[Diachi]
           ,[Nguoilienhe]
           ,[Dienthoai]
           ,[Hieuluc]
           ,[HinhthucTT]
           ,[HanTT]
           ,[PTVanchuyen]
           ,[TW1]
           ,[TW2]
           ,[Songaykhuon]
           ,[Trangthai]
           ,[Solan]
           ,[Ngaychungtu]
           ,[Ngayduyet]
           ,[Ngoaite]
           ,[DKTT]
           ,[ThoihanTT]
           ,[Maxno]
           ,[TileTT]
           ,[SongayLH]
           ,[GhichuNB]
           ,[Tigia]
           ,[CreateBy]
           ,[EditBy]
           ,[EditDate])
     
	  select [Maphieu]
           ,[Ngaylap]
           ,[Makh]
           ,[Tenkh]
           ,[Ghichu],
           [Diachi]
           ,[Nguoilienhe]
           ,[Dienthoai]
           ,[Hieuluc]
           ,[HinhthucTT]
           ,[HanTT]
           ,[PTVanchuyen]
           ,[TW1]
           ,[TW2]
           ,[Songaykhuon]
           ,[Trangthai]
           ,[Solan]
           ,Ngaylap
           ,[Ngayduyet]
           ,[Ngoaite]
           ,[DKTT]
           ,[ThoihanTT]
           ,[Maxno]
           ,[TileTT]
           ,[SongayLH]
           ,[GhichuNB]
           ,[Tigia]
           ,uname
           ,uname
           ,Ngaylap
	 from  Bao_Gia where year(Ngaylap)=2025
GO

INSERT INTO tinthanhnew.dbo.[Phieubaogia_CT]
           ([PhieubaogiaId]
           ,[Stt]
           ,[Masp]
           ,[Tensp]
           ,[Donvi]
           ,[Dongia]
           ,[Vat]
           ,[Thanhtien]
           ,[Trongluong]
           ,[Matdo]
           ,[Loai]
           ,[Socav]
           ,[Khomay]
           ,[DongiaNT]
           ,[ThanhtienNT]
           ,[GiaSC]
           ,[GiaSCNT]
           ,[GiaCu]
           ,[GiaCuNT]
           ,[DongiaKG]
           ,[SoluongBG]
           ,[Tilevon]
           ,[gc]
           ,[Mabo]
           ,[SoluongKH]
           ,[GiaKH]
           ,[GiaKH_USD])
 
 select    b.id
           ,ROW_NUMBER()  OVER(PARTITION BY b.id ORDER BY MAsp ASC) 
 
           ,[Masp]
           ,[Tensp]
           ,[Donvi]
           ,[Dongia]
           ,[Vat]
           ,[Thanhtien]
           ,[Trongluong]
           ,[Matdo]
           ,[Loai]
           ,[Socav]
           ,[Khomay]
           ,[DongiaNT]
           ,[ThanhtienNT]
           ,[GiaSC]
           ,[GiaSCNT]
           ,[GiaCu]
           ,[GiaCuNT]
           ,[DongiaKG]
           ,[SoluongBG]
           ,[Tilevon]
           ,[gc]
           ,[Mabo]
           ,[SoluongKH]
           ,[GiaKH]
           ,[GiaKH_USD] 
		     from  tinthanh.dbo.Baogia_CT a inner join  tinthanhnew.dbo.Phieubaogia b on a.Maphieu=b.Maphieu 
